/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyGames;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author RaihanRafiq
 */
public class FromGame extends javax.swing.JFrame {
    GamePlay play = new GamePlay(0,0);
    ImageIcon gunting = new ImageIcon("D:\\Project1\\src\\main\\java\\MyGames\\GUNTING.png");
    ImageIcon batu = new ImageIcon("D:\\Project1\\src\\main\\java\\MyGames\\BATU.png");
    ImageIcon kertas = new ImageIcon("D:\\Project1\\src\\main\\java\\MyGames\\KERTAS.png");
    int ronde, akhir;
    String name; 
    FormRonde round = new FormRonde();
    /**
     * Creates new form FromGame
     */
    public FromGame(int batas, String nama) {
        initComponents();
        akhir = batas;
        name = nama;
        setLocationRelativeTo(null);
        setResizable(false);
        tRound.setEditable(false);
        tNumber.setEditable(false);
        lNama.setText(name);
        ronde = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lskorYou = new javax.swing.JLabel();
        lskorCom = new javax.swing.JLabel();
        lhasil = new javax.swing.JLabel();
        bGunting = new javax.swing.JButton();
        bBatu = new javax.swing.JButton();
        bKertas = new javax.swing.JButton();
        lNama = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tRound = new javax.swing.JTextField();
        lGambarYou = new javax.swing.JLabel();
        lGambarCom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        lskorYou.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lskorYou.setForeground(new java.awt.Color(255, 255, 255));
        lskorYou.setText("0");

        lskorCom.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lskorCom.setForeground(new java.awt.Color(255, 255, 255));
        lskorCom.setText("0");

        lhasil.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lhasil.setForeground(new java.awt.Color(255, 255, 255));
        lhasil.setText("READY !!!");

        bGunting.setBackground(new java.awt.Color(0, 255, 102));
        bGunting.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bGunting.setForeground(new java.awt.Color(255, 255, 255));
        bGunting.setText("SCISSORS");
        bGunting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuntingActionPerformed(evt);
            }
        });

        bBatu.setBackground(new java.awt.Color(255, 153, 204));
        bBatu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bBatu.setForeground(new java.awt.Color(255, 255, 255));
        bBatu.setText("ROCK");
        bBatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatuActionPerformed(evt);
            }
        });

        bKertas.setBackground(new java.awt.Color(102, 204, 255));
        bKertas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bKertas.setForeground(new java.awt.Color(255, 255, 255));
        bKertas.setText("PAPER");
        bKertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKertasActionPerformed(evt);
            }
        });

        lNama.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lNama.setForeground(new java.awt.Color(255, 255, 255));
        lNama.setText("YOU");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COMPUTER");

        tNumber.setBackground(new java.awt.Color(0, 102, 102));
        tNumber.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        tNumber.setForeground(new java.awt.Color(255, 255, 255));
        tNumber.setText("1");
        tNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNumberActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tRound.setBackground(new java.awt.Color(0, 102, 102));
        tRound.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        tRound.setForeground(new java.awt.Color(255, 255, 255));
        tRound.setText("ROUND");

        lGambarYou.setIcon(new javax.swing.ImageIcon("D:\\Project1\\src\\main\\java\\MyGames\\BATU.png")); // NOI18N

        lGambarCom.setIcon(new javax.swing.ImageIcon("D:\\Project1\\src\\main\\java\\MyGames\\BATU.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(440, Short.MAX_VALUE)
                                .addComponent(tRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(lNama)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(lGambarYou, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                        .addComponent(lskorYou)
                                        .addGap(130, 130, 130))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bGunting)
                                        .addGap(39, 39, 39)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bBatu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lhasil))
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(lskorCom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                                .addComponent(lGambarCom))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(82, 82, 82))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(bKertas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lNama))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lGambarCom)
                            .addComponent(lGambarYou, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lhasil)
                                    .addComponent(lskorCom))
                                .addGap(123, 123, 123))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lskorYou)
                                .addGap(115, 115, 115)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bGunting)
                            .addComponent(bBatu)
                            .addComponent(bKertas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNumberActionPerformed

    private void bGuntingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuntingActionPerformed
        // TODO add your handling code here:
        ronde++;
        lGambarYou.setIcon(gunting);
        if (play.getCom().equals("g")){
            lGambarCom.setIcon(gunting);
        }else if (play.getCom().equals("b")){
            lGambarCom.setIcon(batu);
        }else if (play.getCom().equals("k")){
            lGambarCom.setIcon(kertas);
        }
        play.setYou("g");
        play.seleksiHasil();
        lskorYou.setText(Integer.toString(play.getSkorYou()));
        lskorCom.setText(Integer.toString(play.getSkorCom()));
        lhasil.setText(play.getHasil());
        play.pindahPos();
        if (ronde == akhir){
            play.toHasil();
            JOptionPane.showMessageDialog(this, play.getHasil(),"info", JOptionPane.INFORMATION_MESSAGE);
            int dialog = JOptionPane.showConfirmDialog(this, "APAKAH KAMU MAU LANJUT ?");
            if (dialog == JOptionPane.YES_OPTION){
                setVisible(false);
                round.setVisible(true);
            }else{
                dispose();
            }
        }
        tNumber.setText(Integer.toString(ronde + 1));
        
    }//GEN-LAST:event_bGuntingActionPerformed

    private void bBatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatuActionPerformed
        // TODO add your handling code here:
        ronde++;
        lGambarYou.setIcon(batu);
        if (play.getCom().equals("g")){
            lGambarCom.setIcon(gunting);
        }else if (play.getCom().equals("b")){
            lGambarCom.setIcon(batu);
        }else if (play.getCom().equals("k")){
            lGambarCom.setIcon(kertas);
        }
        play.setYou("b");
        play.seleksiHasil();
        lskorYou.setText(Integer.toString(play.getSkorYou()));
        lskorCom.setText(Integer.toString(play.getSkorCom()));
        lhasil.setText(play.getHasil());
        play.pindahPos();
        if (ronde == akhir){
            play.toHasil();
            JOptionPane.showMessageDialog(this, play.getHasil(),"info", JOptionPane.INFORMATION_MESSAGE);
            int dialog = JOptionPane.showConfirmDialog(this, "APAKAH KAMU MAU LANJUT ?");
            if (dialog == JOptionPane.YES_OPTION){
                setVisible(false);
                round.setVisible(true);
            }else{
                dispose();
            }
        }
        tNumber.setText(Integer.toString(ronde + 1));
    }//GEN-LAST:event_bBatuActionPerformed

    private void bKertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKertasActionPerformed
        // TODO add your handling code here:
        ronde++;
        lGambarYou.setIcon(kertas);
        if (play.getCom().equals("g")){
            lGambarCom.setIcon(gunting);
        }else if (play.getCom().equals("b")){
            lGambarCom.setIcon(batu);
        }else if (play.getCom().equals("k")){
            lGambarCom.setIcon(kertas);
        }
        play.setYou("k");
        play.seleksiHasil();
        lskorYou.setText(Integer.toString(play.getSkorYou()));
        lskorCom.setText(Integer.toString(play.getSkorCom()));
        lhasil.setText(play.getHasil());
        play.pindahPos();
        if (ronde == akhir){
            play.toHasil();
            JOptionPane.showMessageDialog(this, play.getHasil(),"info", JOptionPane.INFORMATION_MESSAGE);
            int dialog = JOptionPane.showConfirmDialog(this, "APAKAH KAMU MAU LANJUT ?");
            if (dialog == JOptionPane.YES_OPTION){
                setVisible(false);
                round.setVisible(true);
            }else{
                dispose();
            }
        }
        tNumber.setText(Integer.toString(ronde + 1));
    }//GEN-LAST:event_bKertasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "Yakin Ingin Keluar ?");
        if (exit == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "SAMPAI JUMPA KEMBALI", "INFO", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatu;
    private javax.swing.JButton bGunting;
    private javax.swing.JButton bKertas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lGambarCom;
    private javax.swing.JLabel lGambarYou;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lhasil;
    private javax.swing.JLabel lskorCom;
    private javax.swing.JLabel lskorYou;
    private javax.swing.JTextField tNumber;
    private javax.swing.JTextField tRound;
    // End of variables declaration//GEN-END:variables
}
